### ISSUE TITLE
wrong_expected_version

### ISSUE THREAD

**Issue by davich** [commanded/eventstore#84]
I'm getting a 

> no case clause matching: {{:error, :wrong_expected_version}, %EventStore.Streams.Stream{serializer: Commanded.Serialization.JsonSerializer, stream_id: 38, stream_uuid: "f4b16d5f-d731-4d89-bd60-071d79ccd50c", stream_version: 0}}

Any idea what might be causing this? I upgraded to v0.12.0 not long ago. Might this be related?

Thanks

**Comment by slashdotdash** [comment]
Did you run the upgrade script(s) against the PostgreSQL database when you upgraded the EventStore? 

You need to run each migration script after the version you were on: 

https://github.com/commanded/eventstore/tree/v0.12.1/scripts/upgrades

The alternative is to drop and create the database again: `mix do event_store.drop, event_store.create`

**Comment by davich** [comment]
Just to follow up on this. I had run the migrations.

The problem seemed to be that the event_id in the event_counter table had fallen behind the latest event_id in the events table. So when it was trying to insert a new event, it was getting a primary key violation, and the code at appender.ex:77 was handling a "unique_violation" and returning a "wrong_expected_version", for some reason.

Any idea why the event_counter table got out of sync?

Thanks

**Comment by slashdotdash** [comment]
Thanks for tracking down the root cause. Do you remember which version of the Event Store database you were upgrading from and/or which migration script caused the discrepancy? 

This isn't an issue I've encountered; I don't suppose you had took a backup of the database before upgrading so that you can retry? 

If it's a dev database then I would recommend recreating it using: `mix do event_store.drop, event_store.create, event_store.init`

**Comment by davich** [comment]
Yep, We upgraded from version 0.9.0 to 0.11.0. Not sure which (if any) migration script caused the discrepancy. This was on our staging environment, so it's possible something weird happened. 

Thanks for your help with this.
