### ISSUE TITLE
Make event_store Mix task logic available independently of Mix

### ISSUE THREAD

**Issue by uberbrodt** [commanded/eventstore#87]
Distillery releases do not have `Mix` or the commandline tool `mix` available. In order to better support this deployment option, it would be useful to have the functionality of the following tasks available without any Mix dependencies:

* `event_store.create`
* `event_store.drop`
* `event_store.init`
* `event_store.migrate`

**Comment by bamorim** [comment]
@uberbrodt how things are going with this? Are you thinking about implementing it?

Some people commented on #22 that one idea would be to use Ecto as a backend.

Since Ecto already has the concepts of migrations, this might solve the problem with the `event_store.migrate` piping to psql.

It should also be more straightforward to solve #73 and #76.

This would also be great for testing since we could use `Ecto.Sandbox`.

My only concern with that is that this would increase the dependencies.

**Comment by uberbrodt** [comment]
@bamorim I think I will have time soon to look at this again and do a PR. One question I have, is do we need to be able to rollback migrations? Currently you can only go forward, which is _probably_ fine, but I suppose there might be a case where rollback would be handy.

**Comment by slashdotdash** [comment]
@uberbrodt The migration scripts are created by hand, there's no support for rollback. Instead you'd need to a backup of the database before migrating and restore the backup to go backwards.
